### ISSUE TITLE
Unknown argument is being supplied to the main constructor

### ISSUE THREAD

**Issue by kasra-keshavarz** [ShervanGharari/EASYMORE#70]
In a general case, an unknown option/argument is being supplied to the main constructor using CLI:

```console
Traceback (most recent call last):
  File "/home/kasra545/virtual-envs/scienv/bin/easymore", line 8, in <module>
    sys.exit(main())
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Compiler/gcc9/eccodes/2.25.0/lib/python3.10/site-packages/click-8.1.2-py3.10.egg/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Compiler/gcc9/eccodes/2.25.0/lib/python3.10/site-packages/click-8.1.2-py3.10.egg/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Compiler/gcc9/eccodes/2.25.0/lib/python3.10/site-packages/click-8.1.2-py3.10.egg/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Compiler/gcc9/eccodes/2.25.0/lib/python3.10/site-packages/click-8.1.2-py3.10.egg/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Compiler/gcc9/eccodes/2.25.0/lib/python3.10/site-packages/click-8.1.2-py3.10.egg/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/kasra545/virtual-envs/scienv/lib/python3.10/site-packages/easymore/scripts/main.py", line 147, in from_conf
    json_exp = Easymore.from_json_file(json)
  File "/home/kasra545/virtual-envs/scienv/lib/python3.10/site-packages/easymore/remapper.py", line 352, in from_json_file
    return cls.from_dict(json_dict)
  File "/home/kasra545/virtual-envs/scienv/lib/python3.10/site-packages/easymore/remapper.py", line 324, in from_dict
    return cls(**init_dict)
TypeError: Easymore.__init__() got an unexpected keyword argument 'overwrite_remapped_nc'
```

**Comment by ShervanGharari** [comment]
I think you did not update the code (the option to CLI). Version 2 does not have `overriwte_remapped_nc` anymore and I have moved it from here:
https://github.com/ShervanGharari/EASYMORE/blob/develop_2.0.0/src/easymore/scripts/_cli_options.py

**Comment by kasra-keshavarz** [comment]
OK great, I checked and it has been removed.

If that option is ever needed, `required` could also be turned into `False` in the options dictionary.
