### ISSUE TITLE
Small issue with job submission when `SLURM` file is provided externally

### ISSUE THREAD

**Issue by kasra-keshavarz** [ShervanGharari/EASYMORE#80]
There is an issue when SLURM job submission files are provided externally. The error is like the following:
```python
Traceback (most recent call last):
  File "/home/kasra545/virtual-envs/scienv2/bin/easymore", line 33, in <module>
    sys.exit(load_entry_point('easymore', 'console_scripts', 'easymore')())
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Compiler/gcc9/eccodes/2.25.0/lib/python3.10/site-packages/click-8.1.2-py3.10.egg/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Compiler/gcc9/eccodes/2.25.0/lib/python3.10/site-packages/click-8.1.2-py3.10.egg/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Compiler/gcc9/eccodes/2.25.0/lib/python3.10/site-packages/click-8.1.2-py3.10.egg/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Compiler/gcc9/eccodes/2.25.0/lib/python3.10/site-packages/click-8.1.2-py3.10.egg/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Compiler/gcc9/eccodes/2.25.0/lib/python3.10/site-packages/click-8.1.2-py3.10.egg/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/kasra545/github-repos/EASYMORE/src/easymore/scripts/main.py", line 113, in from_cli
    submit_hpc_job(kwargs[cache],
  File "/home/kasra545/github-repos/EASYMORE/src/easymore/scripts/main.py", line 168, in submit_hpc_job
    job_str = pkgutil.get_data(__name__, job_conf_file).decode()
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.10.2/lib/python3.10/pkgutil.py", line 639, in get_data
    return loader.get_data(resource_name)
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/home/kasra545/github-repos/EASYMORE/src/easymore/scripts/home/kasra545/scratch/easymore-job.slurm'
```

The suggested solution is to make sure if the file is externally provided, then the `pkgutil` in the following lines are not used, as files starting with `'/' are not allowed:
https://github.com/ShervanGharari/EASYMORE/blob/8cc7c102c78bb2eace0d86cde4486011ab77db17/src/easymore/scripts/main.py#L165

**Comment by kasra-keshavarz** [comment]
Resolved with #82. Thank you @ShervanGharari for the confirmation.
